# Generated by Django 5.0.3 on 2024-05-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link', models.CharField(blank=True, max_length=100, null=True)),
                ('github_stars', models.IntegerField(blank=True, null=True)),
                ('whatsapp_members', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pioneer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pioneer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, default='images/user-default.jpg', null=True, upload_to='images/')),
                ('pioneer_social_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
