# Generated by Django 5.0.2 on 2025-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pioneer',
            options={'ordering': ['-id'], 'verbose_name': 'Pioneer', 'verbose_name_plural': 'Pioneers'},
        ),
        migrations.AddField(
            model_name='pioneer',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='pioneer',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Position/Title'),
        ),
        migrations.AlterField(
            model_name='pioneer',
            name='pioneer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pioneer',
            name='pioneer_social_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Social Link'),
        ),
        migrations.AlterField(
            model_name='pioneer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='pioneers/'),
        ),
    ]
