# Generated by Django 5.0.2 on 2026-02-24 22:18

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='history_thumbnails/')),
                ('content_english', ckeditor.fields.RichTextField(blank=True)),
                ('content_igala', ckeditor.fields.RichTextField(blank=True)),
                ('audio_english', models.FileField(blank=True, null=True, upload_to='history_audio/')),
                ('audio_igala', models.FileField(blank=True, null=True, upload_to='history_audio/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History Article',
                'verbose_name_plural': 'History Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='history_thumbnails/')),
                ('content_english', ckeditor.fields.RichTextField(blank=True)),
                ('content_igala', ckeditor.fields.RichTextField(blank=True)),
                ('audio_english', models.FileField(blank=True, null=True, upload_to='history_audio/')),
                ('audio_igala', models.FileField(blank=True, null=True, upload_to='history_audio/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_notes', models.TextField(blank=True, null=True)),
                ('approved_article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission', to='history.historyarticle')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_histories', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_history_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending History',
                'verbose_name_plural': 'Pending Histories',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
