# Generated by Django 5.0.3 on 2026-02-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('viewed_date', models.DateField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='blog.blogpost')),
            ],
        ),
        migrations.AddConstraint(
            model_name='blogpostview',
            constraint=models.UniqueConstraint(fields=('post', 'ip_hash', 'viewed_date'), name='unique_blog_view_per_day'),
        ),
    ]
