# Generated by Django 5.0.3 on 2024-05-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igala_example', models.CharField(max_length=200)),
                ('english_meaning', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.FileField(blank=True, null=True, upload_to='word_sounds/')),
                ('dialects', models.CharField(blank=True, max_length=200, null=True)),
                ('related_terms', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Word',
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('examples', models.ManyToManyField(to='dictionary.example')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.partofspeech')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='dictionary.words')),
            ],
        ),
    ]
