# Generated by Django 5.0.3 on 2024-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='related_terms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
