# Generated by Django 5.0.3 on 2024-03-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='related_terms',
            field=models.ManyToManyField(blank=True, to='dictionary.words'),
        ),
    ]
