# Generated by Django 5.0.3 on 2024-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_words_related_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='related_terms',
        ),
        migrations.AddField(
            model_name='words',
            name='related_terms',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
