# Generated by Django 5.0.2 on 2025-10-21 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_words_contributor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_words_count', models.IntegerField(default=0)),
                ('pending_words_count', models.IntegerField(default=0)),
                ('rejected_words_count', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('first_contribution', models.DateTimeField(blank=True, null=True)),
                ('last_contribution', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution Statistics',
                'verbose_name_plural': 'Contribution Statistics',
            },
        ),
        migrations.CreateModel(
            name='PendingMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.partofspeech')),
            ],
            options={
                'verbose_name': 'Pending Meaning',
                'verbose_name_plural': 'Pending Meanings',
            },
        ),
        migrations.CreateModel(
            name='PendingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igala_example', models.CharField(max_length=200)),
                ('english_meaning', models.CharField(max_length=200)),
                ('pending_meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_examples', to='dictionary.pendingmeaning')),
            ],
            options={
                'verbose_name': 'Pending Example',
                'verbose_name_plural': 'Pending Examples',
            },
        ),
        migrations.CreateModel(
            name='PendingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation_file', models.FileField(blank=True, null=True, upload_to='pending_sounds/')),
                ('dialects', models.CharField(blank=True, max_length=200, null=True)),
                ('related_terms', models.CharField(blank=True, max_length=200, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes about the review', null=True)),
                ('approved_word', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission', to='dictionary.words')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_words', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_word_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Word Submission',
                'verbose_name_plural': 'Pending Word Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='pendingmeaning',
            name='pending_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_meanings', to='dictionary.pendingword'),
        ),
    ]
