# Generated by Django 5.0.2 on 2026-01-30 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_contributionstats_pendingmeaning_pendingexample_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingExampleContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igala_example', models.CharField(max_length=200)),
                ('english_meaning', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes about the review', null=True)),
                ('approved_example', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_contribution', to='dictionary.example')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_example_contributions', to='dictionary.meaning')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_example_contributions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_example_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Example Contribution',
                'verbose_name_plural': 'Pending Example Contributions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
