# Generated by Django 5.0.3 on 2024-04-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_remove_words_related_terms_words_related_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigureOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='words',
            name='example_meaning',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='dialects',
            field=models.ManyToManyField(blank=True, related_name='words', to='dictionary.dialect'),
        ),
        migrations.AddField(
            model_name='words',
            name='figure_of_speech',
            field=models.ManyToManyField(blank=True, related_name='words', to='dictionary.figureofspeech'),
        ),
    ]
