# Generated by Django 5.0.2 on 2026-01-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_add_pending_example_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
