# Generated by Django 5.0.3 on 2024-04-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_figureofspeech_words_example_meaning_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FigureOfSpeech',
            new_name='PartOfSpeech',
        ),
        migrations.RenameField(
            model_name='words',
            old_name='figure_of_speech',
            new_name='part_of_speech',
        ),
    ]
