# Generated by Django 5.0.2 on 2026-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_words_unique_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='example_sounds/'),
        ),
    ]
