# Generated by Django 5.0.2 on 2026-02-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_example_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionstats',
            name='approved_histories_count',
            field=models.IntegerField(default=0),
        ),
    ]
