# Generated by Django 5.0.2 on 2026-02-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_contributionstats_approved_histories_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
